#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-imagesize
Version  : 1.1.0
Release  : 36
URL      : https://files.pythonhosted.org/packages/41/f5/3cf63735d54aa9974e544aa25858d8f9670ac5b4da51020bbfc6aaade741/imagesize-1.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/41/f5/3cf63735d54aa9974e544aa25858d8f9670ac5b4da51020bbfc6aaade741/imagesize-1.1.0.tar.gz
Summary  : Getting image size from png/jpeg/jpeg2000/gif file
Group    : Development/Tools
License  : MIT
Requires: deprecated-imagesize-license = %{version}-%{release}
Requires: deprecated-imagesize-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : setuptools-legacypython

%description
imagesize
=============
.. image:: https://travis-ci.org/shibukawa/imagesize_py.svg?branch=master
:target: https://travis-ci.org/shibukawa/imagesize_py

%package legacypython
Summary: legacypython components for the deprecated-imagesize package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-imagesize package.


%package license
Summary: license components for the deprecated-imagesize package.
Group: Default

%description license
license components for the deprecated-imagesize package.


%package python
Summary: python components for the deprecated-imagesize package.
Group: Default

%description python
python components for the deprecated-imagesize package.


%prep
%setup -q -n imagesize-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554321050
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-imagesize
cp LICENSE.rst %{buildroot}/usr/share/package-licenses/deprecated-imagesize/LICENSE.rst
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-imagesize/LICENSE.rst

%files python
%defattr(-,root,root,-)
